### PR TITLE
Distribute type data (PEP 561)

### PR DESCRIPTION
**Pull request by hukkin**
- Add type annotations. Use mypy to lint them
- Distribute type data (PEP 561)

### CODE REVIEW

**Comment by fiatjaf** [comment]
Can you make Travis check type data? Is that possible?

**Comment by hukkin** [comment]
This PR runs `pip install mypy==0.761 && mypy .` in travis. If this is what you meant, then it's already there :)

**Comment by hukkin** [comment]
@fiatjaf I added one more commit that makes `encode()` return `None` if `convertbits()` returns `None`. Before it used to throw an unhandled, unexpected TypeError.

**Comment by hukkin** [comment]
Also speaking of Travis, please have a look at https://github.com/fiatjaf/bech32/issues/2

**Pull request merged**
